steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/kubernetest-assignment/kubernetes-repository/container-2', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/kubernetest-assignment/kubernetes-repository/container-2:latest']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
  - 'container'
  - 'clusters'
  - 'get-credentials'
  - 'kubernetes-assignment-cluster'
  - '--zone'
  - 'us-central1-a'
  - '--project'
  - 'kubernetest-assignment'
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'kubectl'
  args:
  - 'apply'
  - '-f'
  - 'kubernetes/deployment.yaml'

options:
  logging: CLOUD_LOGGING_ONLY
