apiVersion: apps/v1
kind: Deployment
metadata: 
  name: container-2-deployment
  labels:
    app: container-2-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container-2-app
  template:
    metadata:
      labels:
        app: container-2-app
    spec:
      containers:
        - name: container-2
          image: us-central1-docker.pkg.dev/kubernetest-assignment/kubernetes-repository/container-2:latest
          ports:
            - containerPort: 7000
          volumeMounts:
            - mountPath: /Savan_PV_dir
              name: data-volume
      imagePullSecrets:
        - name: my-image-pull-secret
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: kubernetes-assignment-pvc
---

apiVersion: v1
kind: Service
metadata:
  name: container2-service
spec:
  selector:
    app:  container-2-app
  type:  ClusterIP
  ports:
  - protocol: TCP
    port: 81
    targetPort: 7000